### ISSUE TITLE
Curious on the automatisation level

### ISSUE THREAD

**Issue by tukoz** [jappeace/distrowatch1graph1svg#1]
1. Splendid work already. I mean: woow :-] How much of the total grabbing and rendering have you manage to automatize now?
2. I'd like to check when do the few glitches I've noted happen. E.g. Mandriva (actually _Mandrake_) is a fork of Red Hat and Mageia a fork of Mandriva.

**Comment by jappeace** [comment]
1. The fetch.py command does the screen scraping on the distrowatch. The output of this command has to be inserted into the graph.py command. Which creates a graph/tree like structure from it. Then the svg.py can be used to create the file csv which can be fed into gnuclad which creates the svg for you.

So except for having many steps (which I still have to put in a *.sh file), the process is fully automated. (although do note that the first step takes a while, since it requires loading many individiual html pages on distrowatch).

2. The glitches are problematic. The reason is mainly that distrowatch isn't very precise with the depends on relation. 

My idea was to create an extra data source file to correct this which can also be inserted into the graph.py, or maybe just create an extra step in the pipeline that does correcting. Currenty the graph.py already does some [correcting](https://github.com/jappeace/distrowatch1graph1svg/blob/master/graph.py#L49) just to get the relations to work (partly my own fault btw for wanting the relations to be super explicit ie debian -> kubntu, should be debian -> ubuntu -> kubuntu).

I also don't handle renames very well. I think I could do some extra scraping from distrowatch as renames are often recorded in the parenthesis of depends on (which I just remove right now).

**Comment by jappeace** [comment]
Ok I just fixed the mandriva stuff sort off manually, [here](https://github.com/jappeace/distrowatch1graph1svg/blob/master/correct.py#L91) and [here](https://github.com/jappeace/distrowatch1graph1svg/blob/master/correct.py#L69). If you see any more glitches in the new [result](https://upload.wikimedia.org/wikipedia/commons/1/15/Linux_landscape_2016_II_%28and_bsd%27s%29.png) please let me know.
